<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>SimpleTextDatabase</PackageId>
		<Version>1.9.1</Version>
		<Authors>Ronald Ryan</Authors>
		<Company>Teach Tea Studio</Company>
		<Description>A simple text-based database with basic functionality.</Description>
		<PackageTags>text database orm noSql</PackageTags>
		<Copyright>Copyright © Teach Tea Studio 2024</Copyright>
		<RepositoryUrl>https://github.com/IoannTerrible/WordDataBase</RepositoryUrl>
		<PackageIcon>database.png</PackageIcon>
	</PropertyGroup>
	
	<PropertyGroup>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>

	</PropertyGroup>
	
	<ItemGroup>
		<None Include="database.png" Pack="true" PackagePath="\" />
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
